#!/bin/bash
# Generated by pybuildc

#----------Variables-----------#
PROJECT="clib"
CC="clang"
BUILD_DIR=".build"
CFLAGS=()

#-------------Setup------------#
SCRIPT_DIR=$(dirname "$0")
set -xe
cd $SCRIPT_DIR

BIN=$BUILD_DIR/bin/$PROJECT
mkdir -p $BUILD_DIR/bin
mkdir -p $BUILD_DIR/obj

#---------Compilation---------#
mkdir -p $BUILD_DIR/obj/clib
$CC -Isrc -Wall -Wpedantic -O2 -DNDEBUG -fsanitize=address ${CFLAGS[@]} src/clib/arena.c -o $BUILD_DIR/obj/clib/arena.o -c
mkdir -p $BUILD_DIR/obj/clib
$CC -Isrc -Wall -Wpedantic -O2 -DNDEBUG -fsanitize=address ${CFLAGS[@]} src/clib/str.c -o $BUILD_DIR/obj/clib/str.o -c
ar rcs $BUILD_DIR/bin/libclib.a $BUILD_DIR/obj/clib/arena.o $BUILD_DIR/obj/clib/str.o
