#!/bin/bash
# Generated by pybuildc

#----------Variables-----------#
PROJECT="ctools"
CC="clang"
BUILD_DIR=".build"
CFLAGS=()

#-------------Setup------------#
SCRIPT_DIR=$(dirname "$0")
set -xe
cd $SCRIPT_DIR

BIN=$BUILD_DIR/bin/$PROJECT
mkdir -p $BUILD_DIR/bin
mkdir -p $BUILD_DIR/obj

#---------Compilation---------#
$CC -Isrc -g -Wall -Wextra -Werror -Wpedantic -Wshadow -Wnull-dereference -Wformat=2 ${CFLAGS[@]} src/carena.c src/main.c -o $BIN
