#!/bin/bash
# Generated by pybuildc

#----------Variables-----------#
PROJECT="ctools"
CC="clang"
BUILD_DIR=".build"
CFLAGS=()

#-------------Setup------------#
SCRIPT_DIR=$(dirname "$0")
set -xe
cd $SCRIPT_DIR

BIN=$BUILD_DIR/bin/$PROJECT
mkdir -p $BUILD_DIR/bin
mkdir -p $BUILD_DIR/obj

#---------Compilation---------#
mkdir -p $BUILD_DIR/obj
$CC -Isrc -g -Wall -Wextra -Werror -Wpedantic -Wshadow -Wnull-dereference -Wformat=2 ${CFLAGS[@]} src/arena.c -o $BUILD_DIR/obj/arena.o -c
mkdir -p $BUILD_DIR/obj
$CC -Isrc -g -Wall -Wextra -Werror -Wpedantic -Wshadow -Wnull-dereference -Wformat=2 ${CFLAGS[@]} src/str.c -o $BUILD_DIR/obj/str.o -c
ar rcs $BUILD_DIR/bin/libctools.a $BUILD_DIR/obj/arena.o $BUILD_DIR/obj/str.o
