[pybuildc]
name="cebus"
cflags=[
  "-std=c99",
  "-Werror",
  "-Wall",
  "-Wextra",
  "-Wconversion",
  "-Wpedantic",
   "-fsanitize=address",
]

[exe]
info = "examples/info.c"
word = "examples/word.c"

[[scripts.build]]
cmd = "python3"
args = ["scripts/docs.py"]


[[scripts.build]]
cmd = "python3"
args = ["scripts/single_header.py"]
