[pybuildc]
name="clib"
cflags=[
  "-std=c99",
  "-Wconversion",
  "-Wmissing-prototypes",
  "-Wmissing-declarations",
  "-Wstrict-prototypes",
]

[exe]
info="examples/info.c"
word="examples/word.c"

[[scripts.build]]
cmd="python"
args=["docs.py"]

