[pybuildc]
name="clib"
cflags=[
  "-std=c99",
  "-Wconversion",
  "-Wmissing-prototypes",
  "-Wmissing-declarations",
  "-Wstrict-prototypes",
]

[exe]
info="examples/info.c"
word="examples/word.c"
source="examples/source.c"
json="examples/json.c"

[[scripts.build]]
cmd="python"
args=["scripts/docs.py"]


[[scripts.build]]
cmd="python"
args=["scripts/single_header.py"]