[pybuildc]
name="clib"
cc="clang"
cflags=[
  "-std=c99",
  "-Wconversion",
  "-Wmissing-prototypes",
  "-Wmissing-declarations",
  "-Wstrict-prototypes",
]

[exe]
info="examples/info.c"

[[build.scripts]]
cmd="python3" 
args=["docs.py"]

