[pybuildc]
name="clib"
cflags=[
  "-std=c99",
  "-Wconversion",
  "-Wmissing-prototypes",
  "-Wmissing-declarations",
  "-Wstrict-prototypes",
]

[exe]
info="examples/info.c"
word="examples/word.c"

[[scripts.build]]
cmd="python3"
args=["scripts/docs.py"]


[[scripts.build]]
cmd="python3"
args=["scripts/single_header.py"]
